#!/bin/bash

set -e

echo "🚀 Manual AWS Deployment Guide"
echo "================================"
echo ""
echo "Since EB CLI has issues on Windows, here's how to deploy manually:"
echo ""

echo "📋 Prerequisites:"
echo "1. AWS CLI installed and configured"
echo "2. AWS account with Elastic Beanstalk permissions"
echo "3. Python 3.11"
echo ""

echo "🔧 Steps to deploy:"
echo ""
echo "1. Create a ZIP file of your application:"
echo "   zip -r app.zip . -x '*.pyc' '__pycache__/*' '.git/*' '*.db' 'uploads/*'"
echo ""
echo "2. Go to AWS Elastic Beanstalk Console:"
echo "   https://console.aws.amazon.com/elasticbeanstalk/"
echo ""
echo "3. Create a new application:"
echo "   - Application name: my-job-recommendation-app"
echo "   - Platform: Python 3.11"
echo "   - Platform branch: Python 3.11 running on 64bit Amazon Linux 2"
echo ""
echo "4. Create a new environment:"
echo "   - Environment name: production-env"
echo "   - Domain: (leave default or choose custom)"
echo "   - Instance type: t3.micro"
echo "   - Single instance (for cost savings)"
echo ""
echo "5. Upload your ZIP file and deploy"
echo ""
echo "6. Configure environment variables in the EB console:"
echo "   - SECRET_KEY: your-production-secret-key"
echo "   - ACCESS_TOKEN_EXPIRE_MINUTES: 30"
echo "   - DATABASE_URL: sqlite:///./app.db"
echo "   - CORS_ORIGINS: *"
echo "   - LOG_LEVEL: INFO"
echo "   - MAX_FILE_SIZE_MB: 10"
echo "   - ENVIRONMENT: production"
echo ""
echo "7. Initialize database after deployment:"
echo "   - SSH into the instance"
echo "   - Run: python init_database.py"
echo ""
echo "🌐 Your application will be available at:"
echo "   https://your-environment-name.elasticbeanstalk.com"
echo ""
echo "📊 Monitor your application:"
echo "   - Check logs in EB console"
echo "   - Monitor health status"
echo "   - Set up CloudWatch alarms"
echo ""
echo "🔄 For updates:"
echo "   - Create new ZIP file"
echo "   - Upload and deploy through EB console"
echo ""
echo "✅ Deployment complete!"

